# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: rubricadb
    image: mariadb
    #restart: always
    ports: 
        - 3306:3306
    volumes: 
        - ./mariadata/data:/var/lib/mysql
        - ./mariadata/conf:/etc/mysql
      #- "./mariadata/data:${MARIADB_DATA_DIR}"
      #- "./mariadata/logs:${MARIADB_LOG_DIR}"
      
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
